### ISSUE TITLE
Unneeded rocblas dependency

### ISSUE THREAD

**Issue by dmitrii-galantsev** [PTFOPlayer/rocm_smi_lib_rs#3]
Hey I noticed `roclbas` in some of the install examples in your readme.

Is it really needed? I never have to get rocblas myself.

**Comment by PTFOPlayer** [comment]
To be honest, I haven't checked whether Roclblas is necessary. It will be removed if it isn't needed. 

I am leaving  this issue open for now, it will be closed after testing.

**Comment by PTFOPlayer** [comment]
Yup. you where right, closing.
